### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by bluebrad** [Leantime/leantime#1058]
when navigating the system the popups for training come back even when hitting "do not show again".

https://cdn.discordapp.com/attachments/990002942499250286/1032325586233860167/202210190910-1666195851.png

not a big deal but is annoying when you log back in and there back.

**Comment by marcelfolaron** [comment]
I think this was resolved with this last version update. Can you please verify.

**Comment by bluebrad** [comment]
still not working also updated to the 2.3.2 and its still poping up also 2.3.2 is not working on firefox at all but is fine in chrome
