### ISSUE TITLE
Broken characters in the notification Email

### ISSUE THREAD

**Issue by seonghobae** [Leantime/leantime#76]
![image](https://user-images.githubusercontent.com/8172694/71552015-01346400-2a37-11ea-86f7-2819bd128200.png)

I already converted the database character set with https://github.com/Leantime/leantime/issues/71 this article. However, I can not see any of the utf8mb4 characters in the email correctly.

So, I make a change to https://github.com/Leantime/leantime/blob/b70856eeb8f63ef9455b77c185235c7ead2c0560/src/core/class.mailer.php#L70-L83 like this:
```PHP
            //Use SMTP or php mail().
            if($config->useSMTP === true) {

                $this->mailAgent->SMTPDebug = 0;                                  // Enable verbose debug output
                $this->mailAgent->Timeout = 20;

                $this->mailAgent->isSMTP();                                      // Set mailer to use SMTP
                $this->mailAgent->Host = $config->smtpHosts;          // Specify main and backup SMTP servers
                $this->mailAgent->SMTPAuth = true;                               // Enable SMTP authentication
                $this->mailAgent->Username = $config->smtpUsername;                 // SMTP username
                $this->mailAgent->Password = $config->smtpPassword;                           // SMTP password
                $this->mailAgent->SMTPSecure = $config->smtpSecure;                            // Enable TLS encryption, `ssl` also accepted
                $this->mailAgent->Port = $config->smtpPort;                                    // TCP port to connect to
                $this->mailAgent->CharSet = 'UTF-8';
```

This thing is a famous bug (see https://stackoverflow.com/questions/2491475/phpmailer-character-encoding-issues) then I can fix very fast in a minuite.

Best,
Seongho

**Comment by marcelfolaron** [comment]
Thank you. That saved me a lot of headaches! I'll make sure to include that in the next patch!

**Comment by marcelfolaron** [comment]
Fixed in V2.0.4

**Comment by jerocobo** [comment]
I stilll have this problem in 2.1.4 version and it has this "solution" applied...

**Comment by kenshin33** [comment]
sorry for the necromancing but as @jerocobo said it is still an issue.
sifting through the  code (please keep in mind, I'm no expert), line 86 of class.mailer.php  https://github.com/Leantime/leantime/blob/081d45dd498a466ca1b848cbd224b9d4d8933747/src/core/class.mailer.php#L86 seems misplaced to me, it should be outside of the if block in which it is residing (may be line 70 or 87 +).
